# Markdown
kramdown:
  input:          GFM
  hard_wrap:      false

# Permalinks
permalink:        pretty

# Setup
title:            Christian Fetzer
tagline:
url:              https://fetzerch.github.io
paginate:         5
baseurl:
author:
  name:           Christian Fetzer
  url:            https://fetzerch.github.io
  email:          fetzer.ch@gmail.com
  github:         fetzerch

# Excludes
exclude: [README.md, LICENSE.md, Gemfile*, Rakefile]

# Gems
gems:
    - jekyll-sitemap
    - jekyll-mentions
    - jekyll-paginate
    - jemoji

# Pages
pages_list:
  Projects:       projects
  Archive:        archive
